### ISSUE TITLE
Do not put the point in the field of weight

### ISSUE THREAD

**Issue by Hameloid** [avi-software/weight-tracker#1]
I am trying to put the point in the weight (press the on-screen keyboard) and it does not put.
Meizu MX4 OTA-12, locale ru_RU.UTF-8.

**Comment by avisoftware** [comment]
I can confirm this bug. 
but i think that is bug on the Ubuntu Touch. in en and he local its ok. 
and in ru local i checked another app and the decimal point doesnt work.

I will see what can i do about this.
(if you can check another app that use the numbers only keyboard and report bug in launchpad
actually there is  [old bug](https://bugs.launchpad.net/ubuntu/+source/ubuntu-keyboard/+bug/1488778) 
)

**Comment by avisoftware** [comment]
i open it again the FR_fr also have that bug. 
i should solve it some how

**Comment by colonelinux** [comment]
I confirm the bug with fr_FR

**Comment by dinilu** [comment]
Same thing with Spanish locale (es_ES).

**Comment by avisoftware** [comment]
i hope that this will solve it for you guys. please let me know.
the new version is in the store please update.
thank you
see image this from fr locale 
![photo794402661967439813](https://cloud.githubusercontent.com/assets/10280767/17276175/3c2c4648-5729-11e6-8bde-85273ce89982.jpg)

**Comment by colonelinux** [comment]
OK for fr_FR, thanks

**Comment by dinilu** [comment]
Fixed un Spanish too. Thanks!
