### ISSUE TITLE
Small issues with displayed results on bq E4.5

### ISSUE THREAD

**Issue by Pilot-Pirx** [avi-software/weight-tracker#6]
The displayed result (BMI) is cropped in portrait mode.
The results for weight and BMI are overlapping in landscape mode.
(And I have to lose weight!!!) ;-)

Portrait:
![screenshot20160731_222748900](https://cloud.githubusercontent.com/assets/6442166/17279168/269b4e4c-576e-11e6-8a81-6b7229c390c1.png)

Landscape:
![screenshot20160731_222751876](https://cloud.githubusercontent.com/assets/6442166/17279169/29f2dace-576e-11e6-847e-eb241abae45f.png)

**Comment by avisoftware** [comment]
Thank you!
I am working on redesign it, and it should be solved.
